name: d
visible_name: D (GDC)
version: "4.9-v2.066"
compiler_profile: straitjacket/compiler/d
apparmor_profile: straitjacket/compiled/d
filename: source.d
docker_image: straitjacket/lang-d

file_extensions:
  - d

tests:
  template:
    source: |
      import std.stdio;
      import std.algorithm;
      import std.conv;
      void main() {
        foreach(line; stdin.byLine) {
          writeln(process(line.idup));
        }
      }

      string process(string line) {
        // Process each line of input here
        return line;
      }
    stdin:  "1\n2\n3\n"
    stdout: "\\A1\n2\n3\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  simple:
    source: |
      import std.stdio;
      import std.algorithm;
      import std.conv;
      void main() {
        auto lines = stdin.byLine();
        auto numbers = lines.map!(a => to!int(a) * 2);
        foreach(num; numbers) {
          writeln(num);
        }
      }
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      import std.stdio;
      import std.file;
      int main(char[][] args) {
        std.stdio.writefln("%%s", cast(char[])read("/etc/hosts"));
        return 0;
      }
    stdout:
    stderr: "/etc/hosts: Permission denied"
    exitstatus: 1

  rlimit:
    source: |
      import std.stdio;
      int main() {
        char[] lotsomem = new char[1073741824];
        return 0;
      }
    stdout:
    stderr: core.exception.OutOfMemoryError
    exitstatus: 1
