name: elixir
visible_name: Elixir 1.0.5
version: "1.0.5"
apparmor_profile: straitjacket/interpreter/erlang
filename: main.exs
docker_image: straitjacket-elixir

file_extensions:
  - ex
  - exs

tests:
  simple:
    source: |
      lines = IO.read(:all) |> String.split("\n", trim: true)
      processed = lines
        |> Enum.map(&Integer.parse/1)
        |> Enum.map(&elem(&1, 0))
        |> Enum.map(fn x -> x * 2 end)

      Enum.each(processed, &IO.inspect/1)
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      IO.puts File.read!('/etc/hosts')
    stdout:
    stderr: "could not read file /etc/hosts: permission denied"
    exitstatus: 1

  rlimit:
    source: |
      Enum.take(Stream.cycle([0]), 1073741824)
    stdout:
    stderr: "Cannot allocate [0-9]+ bytes of memory"
    exitstatus: 139
