name: c#
visible_name: C# (mono)
version: 4.0
apparmor_profile: straitjacket/compiled/csharp
filename: source.cs
docker_image: straitjacket-csharp

tests:
  simple:
    source: |
      public class HelloWorld {
         public static void Main() {
           System.Console.WriteLine("hey c# world, sup?");
         }
       }
    stdout: "\\Ahey c# world, sup\\?\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  rlimit:
    source: |
      public class TestRLimit {
        public static void Main() {
          int[] numbers = new int[1073741824];
        }
      }
    stdout:
    stderr: "System.OutOfMemoryException: Out of memory"
    exitstatus: 1

  apparmor:
    source: |
      using System; using System.IO;
      public class TestAppArmor {
        public static void Main() {
          TextReader tr = new StreamReader("/etc/passwd");
          Console.WriteLine(tr.ReadLine());
          tr.Close();
        }
      }
    stdout:
    stderr: Access to the path "/etc/passwd" is denied.
    exitstatus: 1
