name: Javascript
visible_name: Javascript (nodejs 0.12)
apparmor_profile: straitjacket/interpreter/node
filename: source.js
docker_image: jstest

tests:
  simple:
    source: |
      function test() { console.log("hello js"); };
      test();
    stdout: hello js\n
    stderr:
    exitstatus: 0

  apparmor:
    source: |
      var fs: require('fs');
      fs.readFile('/etc/hosts', function (err, data) {
        if (err) throw err;
        console.log(data.toString());
      });
    stdout:
    stderr: "Error: EACCES, open '/etc/hosts'"
    exitstatus: 1

  rlimit:
    source: |
      var buffer1: new Buffer(536870912);
      var buffer2: new Buffer(536870912);
      var buffer3: new Buffer(536870912);
      console.log(buffer1.length + buffer2.length + buffer3.length);
    stdout:
    stderr: "terminate called after throwing an instance of 'std::bad_alloc'"
    exitstatus: -6
