name: ruby
visible_name: Ruby 2.2
version: "2.2"
apparmor_profile: straitjacket/interpreter/ruby
filename: source.rb
docker_image: straitjacket/lang-ruby

file_extensions:
  - rb
  - rbw
  - rbx
  - ruby

tests:
  template:
    source: |
      def process(line)
        # Process each line of input here
        return line
      end

      $stdin.each_line do |line|
        puts process(line)
      end
    stdin:  "1\n2\n3\n"
    stdout: "\\A1\n2\n3\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  simple:
    source: |
      def process(line)
        number = Integer(line) * 2
        number.to_s
      end

      lines = $stdin.each_line
      processed = lines.map { |l| process(l) }
      processed.each { |l| puts l }
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      puts File.read('/etc/hosts')
    stdout:
    stderr: "Permission denied @ rb_sysopen - /etc/hosts \\(Errno::EACCES\\)"
    exitstatus: 1

  rlimit:
    source: |
      x = [0] * 1073741824
    stdout:
    stderr: "failed to allocate memory \\(NoMemoryError\\)"
    exitstatus: 1
