name: php
visible_name: PHP 5
version: "5.6.9"
apparmor_profile: straitjacket/interpreter/default
filename: source.php
docker_image: straitjacket-php

file_extensions:
  - php
  - php5

tests:
  template:
    source: |
      <?php

      while (FALSE !== ($line = fgets(STDIN))) {
        $lines[] = $line;
      }

      foreach ($lines as $line) {
        // Process each line of input here
        $processed[] = chop($line);
      }

      foreach ($processed as $line) {
        echo "$line\n";
      }

      ?>
    stdin:  "1\n2\n3\n"
    stdout: "\\A1\n2\n3\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  simple:
    source: |
      <?php

      while (FALSE !== ($line = fgets(STDIN))) {
        $lines[] = $line;
      }

      foreach ($lines as $line) {
        $processed[] = $line * 2;
      }

      foreach ($processed as $line) {
        echo "$line\n";
      }

      ?>
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      <?php
        $fh = fopen("/etc/hosts", 'r');
        echo fread($fh, filesize("/etc/hosts"));
        fclose($fh)
      ?>
    stdout: "\\A\nWarning: fopen\\(/etc/hosts\\): failed to open stream: Permission denied in"
    stderr: "\\A\\z"
    exitstatus: 0

  rlimit:
    source: |
      <?php echo pcntl_fork(); ?>
    stdout: "\\A\nWarning: pcntl_fork\\(\\): Error 11"
    stderr: "\\A\\z"
    exitstatus: 0
