name: c
visible_name: C (GCC)
version: "C11"
compiler_profile: straitjacket/compiler/c
apparmor_profile: straitjacket/compiled/c
filename: source.c
docker_image: straitjacket-c

tests:
  simple:
    source: |
      #include <stdio.h>
      int main(int argc, char** argv) {
        printf("c compilation succeeded\n");
        return 0;
      }
    stdout: "\\Ac compilation succeeded\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      #include <stdio.h>
      #include <errno.h>
      int main(int argc, char** argv) {
        if(fopen("/etc/hosts", "r")) {
          printf("opened\n");
          return 0;
        } else {
          printf("not opened: %d\n", errno);
          return 1;
        }
      }
    stdout: "\\Anot opened: 13\\n\\z"
    stderr:
    exitstatus: 1

  rlimit:
    source: |
      #include <stdio.h>
      int main(int argc, char** argv) {
        int TOO_MANY = 1073741824;
        int *lots_of_ints = malloc(TOO_MANY * sizeof(int));
        if (NULL == lots_of_ints) {
          return 1;
        }
        return 0;
      }
    stdout: "\\A\\z"
    stderr: "\\A\\z"
    exitstatus: 1
