name: coffeescript
visible_name: CoffeeScript (1.9.0)
version: "1.9.0"
apparmor_profile: straitjacket/interpreter/coffee
filename: source.coffee
docker_image: straitjacket-coffeescript

file_extensions:
  - coffee

tests:
  simple:
    source: |
      readStdin = (callback) ->
        data = ""
        process.stdin.resume()
        process.stdin.setEncoding 'utf8'
        process.stdin.on 'data', (chunk) -> data += chunk.toString()

        return process.stdin.on 'end', () ->
          lines = data.split(/\n/)
          lines.pop()
          callback(lines)

      processLine = (line) ->
        number = +line
        number * 2

      readStdin (lines) ->
        console.log processLine line for line in lines
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      fs = require 'fs'
      fs.readFile '/etc/hosts', (err, data) ->
        throw err if err
        console.log data.toString()
    stdout:
    stderr: "Error: EACCES, open '/etc/hosts'"
    exitstatus: 1

  rlimit:
    source: |
      buffer1 = new Buffer 536870912
      buffer2 = new Buffer 536870912
      buffer3 = new Buffer 536870912
      console.log buffer1.length + buffer2.length + buffer3.length
    stdout:
    stderr: Out Of Memory
    exitstatus: 139