name: lua
visible_name: Lua 5.2
version: "5.2.3"
apparmor_profile: straitjacket/interpreter/default
filename: source.lua
docker_image: straitjacket-lua

file_extensions:
  - lua

tests:
  simple:
    source: |
      local lines = {}

      local function processLine(line)
        local number = tonumber(line)
        return number * 2
      end

      -- read the lines in table 'lines'
      for line in io.lines() do
        table.insert(lines, line)
      end

      -- write all the lines
      for i, l in ipairs(lines) do
        io.write(processLine(l), "\n")
      end
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: print(io.open("/etc/hosts", "r"))
    stdout: "\\Anil\t/etc/hosts: Permission denied\t13\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  rlimit:
    source: print(os.execute("/bin/ls"))
    stdout: Resource temporarily unavailable
    stderr: "\\A\\z"
    exitstatus: 0
