name: perl
visible_name: Perl 5.20
version: "5.20.2"
apparmor_profile: straitjacket/interpreter/perl
filename: source.pl
docker_image: straitjacket/lang-perl

file_extensions:
  - pl
  - plx
  - perl

tests:
  template:
    source: |
      my @arr = <>;
      foreach (@arr) {
        chomp;
        print ($_  . "\n");
      }
    stdin:  "1\n2\n3\n"
    stdout: "\\A1\n2\n3\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  simple:
    source: |
      use strict;
      use Archive::Tar;

      my @arr = <>;
      foreach (@arr) {
        print (($_ * 2) . "\n");
      }
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      open FILE, "/etc/hosts" or die $!;
      while (<FILE>) {
        print $_;
      }
    stdout: "\\A\\z"
    stderr: "\\APermission denied at"
    exitstatus: 13

  rlimit:
    source: |
      my $pid = fork();
      if(defined $pid) { print "defined"; }
      else { print "undefined"; }
      print $pid;
    stdout: "\\Aundefined\\z"
    stderr: "\\A\\z"
    exitstatus: 0
