name: python2
visible_name: Python 2
version: "2.7.10"
apparmor_profile: straitjacket/interpreter/python
filename: source.py
docker_image: straitjacket/lang-python2

tests:
  template:
    source: |
            import sys

            def process(line):
              # Process each line of input here
              return line

            lines = sys.stdin.readlines()

            processed = map(process, lines)
            for line in processed:
                print line.strip()
    stdin:  "1\n2\n3\n"
    stdout: "\\A1\n2\n3\n\\z"
    stderr:
    exitstatus: 0

  simple:
    source: |
            import sys

            def process(line):
              return str(int(line) * 2)

            lines = sys.stdin.readlines()

            processed = map(process, lines)
            for line in processed:
                print line.strip()
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr:
    exitstatus: 0

  apparmor:
    source: |
      print(open("/etc/hosts", 'r').read())
    stdout:
    stderr: "Permission denied: '/etc/hosts'"
    exitstatus: 1

  rlimit:
    source: |
      import os
      print(os.fork())
    stdout:
    stderr: 'OSError: \[Errno 11\] Resource temporarily unavailable'
    exitstatus: 1
